
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [2]:
import numpy as np
mylist = [0,1,2,3,4,5,6,7,8]
myarray = np.array(mylist)
myarray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [35]:
my3Array = myarray.reshape(3,3)
my3Array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Access the element at the second row, second column.


In [36]:
item = my3Array[1,1]
item

4

Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [3]:
calcArray1 = np.array([1,2,3])
calcArray2 = np.array([4,5,6])
print('Addition of the two arrays is:')
print(calcArray1+calcArray2)
print('Subtraction of the two arrays is:')
print(calcArray2-calcArray1)
print('Multiplication of the two arrays is:')
print(calcArray2*calcArray1)
print('Division of the two arrays is:')
print(calcArray2/calcArray1)

Addition of the two arrays is:
[5 7 9]
Subtraction of the two arrays is:
[3 3 3]
Multiplication of the two arrays is:
[ 4 10 18]
Division of the two arrays is:
[4.  2.5 2. ]


Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [45]:
Array = [1,2,3,4,5]
sum = np.sum(Array)
mean = np.mean(Array)
sd = np.std(Array)
print(f"Sum= {sum} \nMean= {mean} \nStandard Deviation= {sd}")

Sum= 15 
Mean= 3.0 
Standard Deviation= 1.4142135623730951


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [48]:
Array = np.array([1,2,3,4,5,6])
Array.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])


# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [51]:
Array = np.random.randint(0,101,size=25)
matrix = Array.reshape(5,5)
matrix

array([[83, 89, 14, 31, 82],
       [31, 28, 31, 74, 83],
       [66, 95, 58, 60, 87],
       [22, 29, 99, 77, 51],
       [23,  8,  2,  3, 60]])

Replace all values in the sub-array with a specific value.


In [53]:
subArray = matrix[1:4,1:4] 
matrix[1:4,1:4] = 5 #5 = subArray
print(subArray)
print('original matrix')
print(matrix)

[[5 5 5]
 [5 5 5]
 [5 5 5]]
original matrix
[[83 89 14 31 82]
 [31  5  5  5 83]
 [66  5  5  5 87]
 [22  5  5  5 51]
 [23  8  2  3 60]]


Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [57]:
Array = np.array( [[1, 2], [3, 4], [5, 6], [7, 8]])
print(Array)
print('Answer')
print(Array[1:2,:])
print(Array[3:4,:])

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Answer
[[3 4]]
[[7 8]]



# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [8]:
array = np.arange(3)
array2D= np.tile(array, (3, 1))
array2D


array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [68]:
array_1d = np.array([1, 2, 3])
print(array_1d+array2D)

[[1 3 5]
 [1 3 5]
 [1 3 5]]


# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [69]:
array1 = np.random.randint(0, 10, size=(3, 3))
array2 = np.random.randint(0, 10, size=(3, 3))
print('array 1:')
print(array1)
print('array 2:')
print(array2)

array 1:
[[6 6 3]
 [5 3 7]
 [6 0 0]]
array 2:
[[9 4 4]
 [0 9 9]
 [7 7 0]]


In [71]:
concatenated_horizontal = np.concatenate((array1, array2), axis=1)

concatenated_vertical = np.concatenate((array1, array2), axis=0)

print("Concatenated Horizontally:")
print(concatenated_horizontal)
print("Concatenated Vertically:")
print(concatenated_vertical)Z

Concatenated Horizontally:
[[6 6 3 9 4 4]
 [5 3 7 0 9 9]
 [6 0 0 7 7 0]]
Concatenated Vertically:
[[6 6 3]
 [5 3 7]
 [6 0 0]
 [9 4 4]
 [0 9 9]
 [7 7 0]]


In [72]:
split_horizontal = np.hsplit(concatenated_horizontal, 2)  
split_vertical = np.vsplit(concatenated_vertical, 2)  
print('split horizontally')
print(split_horizontal)
print('split vertically')
print(split_vertical)


split horizontally
[array([[6, 6, 3],
       [5, 3, 7],
       [6, 0, 0]]), array([[9, 4, 4],
       [0, 9, 9],
       [7, 7, 0]])]
split vertically
[array([[6, 6, 3],
       [5, 3, 7],
       [6, 0, 0]]), array([[9, 4, 4],
       [0, 9, 9],
       [7, 7, 0]])]


# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [74]:
import numpy as np
array = np.array([1, 2, 1, 2, 3, 4, 5, 6, 8, 9, 1, 2, 2, 22, 21, 1, 1, 1, 1, 2, 5])
unique_vals, counts = np.unique(array, return_counts=True)
max_count = np.max(counts)
mode_indices = np.argwhere(counts == max_count).flatten()
print("Mode value:", unique_vals[mode_indices].tolist())
print("Maximum count:", max_count)


Mode value: [1]
Maximum count: 7


# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

